### PR TITLE
Updates for newer Julia version

### PR DESCRIPTION
**Pull request by mforets**
This branch proposes an update of `src` and `test` for Julia v1.0 and v1.1.

### CODE REVIEW

**Comment by mforets** [comment]
Bump 😛

**Comment by dpsanders** [comment]
I think I completely missed this! Thanks a lot! Should I just immediately merge this?

**Comment by mforets** [comment]
Yes, i think so.

Apparently in the new Julia version `X_a^2` does not automatically mean `X_a * X_a`, so i defined a function `sqr` in the tests. Otherwise we would have to extend `^` for `Affine` objects, but i would leave that for another issue.

**Comment by dpsanders** [comment]
You just define literal_pow as is done eg in IntervalArithmetic.jl.

**Comment by dpsanders** [comment]
Thanks a lot!

**Pull request merged**
